[package]
name = "gosh-rust"
version = "0.1.0"
authors = ["Sean Hellum <seanhellum45@gmail.com>", "Teddy Clarke"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "5.0.4"
colored = "1.9"
